spring:
  profiles:
    active: dev


#logging:
#  level:
#    com.example.springbootdubboprivider : debug
#  file: /tmp/comsumer/consumer.log
#  pattern:
#    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5lever %logger[50] -- %msg %n'

#  config: classpath:loggback.xml

seregi.json: "starter"