dubbo:
  application:
    name: springboot-dubbo-consumer

  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181

  monitor:
    protocol: register

  protocol:
#    serialization: kyro
    name: dubbo
    port: 20881

server:
  port: 1111
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000
    database: 1
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html